version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: person_entity
      MYSQL_ROOT_PASSWORD: root

  app:
    # container_name: spring-app
    image: app
    restart: always
    build: .
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

